gem5: update to e2656006df442a995bf80ee03fa9700d6ec14537
The previous commit was failing to build in .fast due to unused variable on DPRINF:

/path/to/linux-kernel-module-cheat/out/gem5/default/build/ARM/dev/arm/gic_v3.cc: In member function 'virtual Tick Gicv3::read(PacketPtr)':
/path/to/linux-kernel-module-cheat/out/gem5/default/build/ARM/dev/arm/gic_v3.cc:94:21: error: unused variable 'context_id' [-Werror=unused-variable]
     const ContextID context_id = pkt->req->contextId();
                     ^~~~~~~~~~